version: 2
build:
  image: latest
sphinx:
  builder: html
python:
  version: 3
  install:
    - requirements: requirements.docs.txt
    - method: pip
      path: .
  system_packages: true
formats: all