name: main
on:
  push:
    branches-ignore:
      - 'release/**'
      - 'master'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: psf/black@stable
      if: matrix.python-version == 3.7 && matrix.os == 'ubuntu-latest'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.test.txt
    - name: Test with unittest
      run: |
        coverage run --source=./hadar -m unittest discover tests
        coverage xml -i
    - name: SonarCloud Scan
      if: matrix.python-version == 3.7 && matrix.os == 'ubuntu-latest'
      uses: sonarsource/sonarcloud-github-action@master
      with:
        name: coverage-report
        path: coverage.xml
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
