name: main
on:
  push:
    branches:
      - 'releases/**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with unittest
      run: |
        pip install coverage
        coverage run --source=./hadar -m unittest discover tests
        coverage xml -i

    - name: Test notebooks
      run: |
        export PYTHONPATH=$(pwd)
        cd examples
        python3 check.py

    - name: Release test.pypi.org
      run: |
        export PYTHONPATH=$(pwd)
        pip install setuptools wheel twine
        python3 setup.py sdist bdist_wheel
        python3 -m twine upload --repository-url https://test.pypi.org/legacy/ dist/* -u __token__ -p $PYPI_TEST_TOKEN
      env:
        PYPI_TEST_TOKEN: ${{ secrets.PYPI_TEST_TOKEN }}