name: staging
on:
  push:
    branches:
      - 'release/**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.test.txt
    - name: Check with black
      uses: psf/black@stable
    - name: Test with unittest
      run: |
        coverage run --source=./hadar -m unittest discover tests
        coverage xml -i

    - name: Test notebooks
      run: |
        git lfs pull
        export PYTHONPATH=$(pwd)
        pip install click jupyter
        cd examples
        python3 utils.py --src=./ --check=./

    - name: Release test.pypi.org
      run: |
        export PYTHONPATH=$(pwd)
        python3 setup.py sdist bdist_wheel
        python3 -m twine upload --repository-url https://test.pypi.org/legacy/ dist/* -u __token__ -p $PYPI_TEST_TOKEN
      env:
        PYPI_TEST_TOKEN: ${{ secrets.PYPI_TEST_TOKEN }}